### ISSUE TITLE
Deleting elements in vector does not reduce file size

### ISSUE THREAD

**Issue by rajathshashidhara** [ExternalMemoryDS/external-mem-ds#18]
elements get deleted but file size is unchanged.

**Comment by ajinkya-k** [comment]
Won't the file size change only after an entire block is removed?

**Comment by rajathshashidhara** [comment]
of course! But, I'm deleting more than one block of elements.
Please look at the test file vector_test.cpp

**Comment by rajathshashidhara** [comment]
@mbiswal94  does #35 solve this bug ?

**Comment by mbiswal94** [comment]
yess the bug is now solved!

**Comment by mbiswal94** [comment]
yes the bug is now fixed!
